globalVariables(unique(
  c(
    # extract_requete:
    "cd_ref",
    "code",
    "commune",
    "commune_nomComm",
    "departement",
    "firstName",
    "id",
    "label",
    "localisation",
    "name",
    "parentCode",
    "presence_label",
    "rang",
    "recensementsTaxon",
    "region",
    "regne",
    "username",
    "vernacularName",
    "xPoint",
    "yPoint",
    # get_taxon_dpt:
    ".",
    # get_taxon_polygon:
    ".",
    "selection_zone",
    # get_taxon_region:
    ".",
    # imp_importer_dump_oison:
    ".",
    # imp_importer_dump_oison : extraire_table:
    ".",
    # imp_importer_dump_oison : imp_trouver_index_fin:
    ".",
    # imp_inpn_habitats_taxon:
    "cd_ref",
    "nom_scientifique",
    "nom_vernaculaire",
    # imp_inpn_maille_taxon:
    "cd_ref",
    "nom_scientifique",
    "nom_vernaculaire",
    # mef_dump_creer_table_taxon_oison:
    '"time"',
    "classe",
    "classe_nombre_individus",
    "classe_nombre_individus_id",
    "co_observateur",
    "code",
    "commentaire",
    "contexte_recherche",
    "contexte_recherche_id",
    "corine_biotope",
    "corine_biotope_id",
    "corine_code",
    "corine_label",
    "email",
    "famille",
    "first_name",
    "geometry",
    "groupe2_inpn",
    "heure",
    "id",
    "initiator_user_id",
    "label",
    "leaf",
    "localisation",
    "longueur_troncon",
    "name",
    "nom",
    "nombre_individu",
    "objectif_recherche",
    "objectif_recherche_id",
    "observation",
    "observation_id",
    "observation_taxon_id",
    "ordre",
    "phylum",
    "prenom",
    "presence_id",
    "rang",
    "recensement_taxon",
    "regne",
    "stade_developpement_id",
    "status",
    "status_id",
    "surface_station",
    "taxon",
    "taxon_code",
    "taxon_presence",
    "taxon_stade_developpement",
    "taxon_vivant_trace",
    "type",
    "type_recherche",
    "type_recherche_id",
    "users",
    "uuid",
    "vernacular_name",
    "vivant_trace_id",
    "x_point",
    "y_point",
    # outil_selection_zone : server:
    "selection_zone",
    # unnest_conditionnel:
    "code",
    "id",
    "id1",
    "label",
    "parentCode",
    # get_table_taxon_sql:
    "con",
    "ST_Intersects",
    "localisation_id",
    "observation_milieu_id",
    "presence",
    "stade_developpement",
    "time",
    "vivant_trace",
    # get_milieu_taxon_sql:
    "activite",
    "chronicite",
    "fonction_observee",
    "impact_situation",
    "milieu_impact",
    "perturbation"
  )
))

